version: "3"
services:
  env:
    build: ./docker
    volumes:
      - ./:/code
    working_dir: /code
    ports:
      - 8888:8888
    command: jupyter notebook --ip=0.0.0.0 --port 8888 --allow-root --no-browser
